run:
  go: '1.24'
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused

linters-settings:
  govet:
    enable-all: false

issues:
  exclude-rules:
    - linters:
        - typecheck
      text: "."
